GID-2478: Introduce identity/authenticated event
iris-events/iris-router pull request #54
Opened 2023-09-01 13:18 UTC by bokas5

2023-09-04 11:49 UTC, ctomc approved these changes

2023-09-04 11:49 UTC, ctomc commented
looks good, will merge once we make sure other parts of backend are ready

2023-09-19 10:48 UTC, tomazic89 approved these changes

2023-09-20 09:56 UTC, ctomc requested changes
Tests fail because SubscribeMessageHandlerTest is wrong and is not sending valid JWT into the request and is mocking way too much stuff

2023-09-20 10:14 UTC, ctomc approved these changes

2023-09-20 10:14 UTC, merged